// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	staffer "air-grating-pms-backend/api/staffer/internal/handler/staffer"
	"air-grating-pms-backend/api/staffer/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/staffer/login",
				Handler: staffer.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/staffer",
				Handler: staffer.InsertStafferHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/staffer",
				Handler: staffer.UpdateStafferInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/staffer",
				Handler: staffer.GetStafferListByEnterpriseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/workshop/staffer",
				Handler: staffer.GetStafferListByWorkshopHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/staffer/password",
				Handler: staffer.UpdateStafferPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/staffer/password",
				Handler: staffer.ResetStafferPasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
