// Code generated by goctl. DO NOT EDIT.
package types

type InsertWorkshopReq struct {
	Name        string `json:"name"`
	Address     string `json:"address,optional"`
	PhoneNumber string `json:"phone_number,optional"`
	ManagerId   int64  `json:"manager_id,optional"`
	Remark      string `json:"remark,optional"`
}

type InsertWorkshopReply struct {
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

type UpdateWorkshopInfoReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Address     string `json:"address,optional"`
	PhoneNumber string `json:"phone_number,optional"`
	ManagerId   int64  `json:"manager_id,optional"`
	Remark      string `json:"remark,optional"`
}

type UpdateWorkshopInfoReply struct {
	Message       string   `json:"message"`
	ChangedFields []string `json:"changed_fields"`
}

type DeleteWorkshopReq struct {
	Id int64 `json:"id"`
}

type DeleteWorkshopReply struct {
	Message string `json:"message"`
}

type WorkshopInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Address     string `json:"address"`
	PhoneNumber string `json:"phone_number"`
	ManagerId   int64  `json:"manager_id"`
	Remark      string `json:"remark"`
}

type GetWorkshopListReq struct {
	PageNumber int32 `json:"pn"`
	PageSize   int32 `json:"ps"`
}

type GetWorkshopListReply struct {
	Message      string         `json:"message"`
	WorkshopList []WorkshopInfo `json:"workshop_list"`
}

type CreateEnterpriseReq struct {
	Name     string `json:"name"`
	BossName string `json:"boss_name"`
	Password string `json:"boss_password"`
	Address  string `json:"address,optional"`
	Remark   string `json:"remark,optional"`
}

type CreateEnterpriseReply struct {
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

type UpdateEnterpriseInfoReq struct {
	Name    string `json:"name,optional"`
	Address string `json:"address,optional"`
	Remark  string `json:"remark,optional"`
}

type UpdateEnterpriseInfoReply struct {
	Message       string   `json:"message"`
	ChangedFields []string `json:"changed_fields"`
}

type DeleteEnterpriseReq struct {
	Password string `json:"password"`
}

type DeleteEnterpriseReply struct {
	Message string `json:"message"`
}

type GetEnterpriseIdByNameReq struct {
	Name string `form:"name"`
}

type GetEnterpriseIdByNameReply struct {
	Id int64 `json:"id"`
}
