// Code generated by goctl. DO NOT EDIT.
package types

type Workshop struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Address     string `json:"address"`
	PhoneNumber string `json:"phone_number"`
	ManagerId   int64  `json:"manager_id"`
	Remark      string `json:"remark"`
}

type CreateWorkshopReq struct {
	Name        string `json:"name"`
	Address     string `json:"address,optional"`
	PhoneNumber string `json:"phone_number,optional"`
	ManagerId   int64  `json:"manager_id,optional"`
	Remark      string `json:"remark,optional"`
}

type CreateWorkshopReply struct {
	Message string `json:"message"`
}

type ChangeWorkshopInfoReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Address     string `json:"address"`
	PhoneNumber string `json:"phone_number"`
	ManagerId   int64  `json:"manager_id"`
	Remark      string `json:"remark"`
}

type ChangeWorkshopInfoReply struct {
	Message string `json:"message"`
}

type PartialChangeWorkshopInfoReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Address     string `json:"address,optional"`
	PhoneNumber string `json:"phone_number,optional"`
	ManagerId   int64  `json:"manager_id,optional"`
	Remark      string `json:"remark,optional"`
}

type PartialChangeWorkshopInfoReply struct {
	Message       string   `json:"message"`
	ChangedFields []string `json:"changed_fields"`
}

type DeleteWorkshopReq struct {
	Id int64 `json:"id"`
}

type DeleteWorkshopReply struct {
	Message string `json:"message"`
}

type RetrieveWorkshopReq struct {
	PageNumber int `json:"pn"`
	PageSize   int `json:"ps"`
}

type RetrieveWorkshopReply struct {
	Message      string     `json:"message"`
	WorkshopList []Workshop `json:"workshop_list"`
}

type CreateEnterpriseReq struct {
	Name     string `json:"name"`
	BossName string `json:"boss_name"`
	Password string `json:"boss_password"`
	Address  string `json:"address,optional"`
	Remark   string `json:"remark,optional"`
}

type CreateEnterpriseReply struct {
	Message string `json:"message"`
}

type ChangeEnterpriseInfoReq struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Remark  string `json:"remark"`
}

type ChangeEnterpriseInfoReply struct {
	Message string `json:"message"`
}

type PartialChangeEnterpriseInfoReq struct {
	Name    string `json:"name,optional"`
	Address string `json:"address,optional"`
	Remark  string `json:"remark,optional"`
}

type PartialChangeEnterpriseInfoReply struct {
	Message       string   `json:"message"`
	ChangedFields []string `json:"changed_fields"`
}

type DeleteEnterpriseReply struct {
	Message string `json:"message"`
}

type GetEnterpriseIdByNameReq struct {
	Name string `form:"name"`
}

type GetEnterpriseIdByNameReply struct {
	Id int64 `json:"id"`
}
