// Code generated by goctl. DO NOT EDIT!
// Source: technology.proto

package server

import (
	"context"

	"air-grating-pms-backend/rpc/technology/internal/logic"
	"air-grating-pms-backend/rpc/technology/internal/svc"
	"air-grating-pms-backend/rpc/technology/pb"
)

type TechnologyServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTechnologyServer
}

func NewTechnologyServer(svcCtx *svc.ServiceContext) *TechnologyServer {
	return &TechnologyServer{
		svcCtx: svcCtx,
	}
}

func (s *TechnologyServer) Insert(ctx context.Context, in *pb.TechnologyInfo) (*pb.InsertResp, error) {
	l := logic.NewInsertLogic(ctx, s.svcCtx)
	return l.Insert(in)
}

func (s *TechnologyServer) Delete(ctx context.Context, in *pb.DeleteReq) (*pb.Empty, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *TechnologyServer) Update(ctx context.Context, in *pb.TechnologyInfo) (*pb.Empty, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *TechnologyServer) FindOneById(ctx context.Context, in *pb.FindOneByIdReq) (*pb.TechnologyInfo, error) {
	l := logic.NewFindOneByIdLogic(ctx, s.svcCtx)
	return l.FindOneById(in)
}

func (s *TechnologyServer) FindListByWorkshop(ctx context.Context, in *pb.FindListByWorkshopReq) (*pb.TechnologyList, error) {
	l := logic.NewFindListByWorkshopLogic(ctx, s.svcCtx)
	return l.FindListByWorkshop(in)
}

func (s *TechnologyServer) FindListByEnterprise(ctx context.Context, in *pb.FindListByEnterpriseReq) (*pb.TechnologyList, error) {
	l := logic.NewFindListByEnterpriseLogic(ctx, s.svcCtx)
	return l.FindListByEnterprise(in)
}
