// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: production_plan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductionPlanClient is the client API for ProductionPlan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductionPlanClient interface {
	Insert(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*InsertResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error)
	Update(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*Empty, error)
	FindOneById(ctx context.Context, in *FindOneByIdReq, opts ...grpc.CallOption) (*ProductionPlanInfo, error)
	FindListByWorkshop(ctx context.Context, in *FindListByWorkshopReq, opts ...grpc.CallOption) (*ProductionPlanList, error)
	FindListByEnterprise(ctx context.Context, in *FindListByEnterpriseReq, opts ...grpc.CallOption) (*ProductionPlanList, error)
}

type productionPlanClient struct {
	cc grpc.ClientConnInterface
}

func NewProductionPlanClient(cc grpc.ClientConnInterface) ProductionPlanClient {
	return &productionPlanClient{cc}
}

func (c *productionPlanClient) Insert(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*InsertResp, error) {
	out := new(InsertResp)
	err := c.cc.Invoke(ctx, "/production_plan.production_plan/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionPlanClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/production_plan.production_plan/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionPlanClient) Update(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/production_plan.production_plan/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionPlanClient) FindOneById(ctx context.Context, in *FindOneByIdReq, opts ...grpc.CallOption) (*ProductionPlanInfo, error) {
	out := new(ProductionPlanInfo)
	err := c.cc.Invoke(ctx, "/production_plan.production_plan/FindOneById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionPlanClient) FindListByWorkshop(ctx context.Context, in *FindListByWorkshopReq, opts ...grpc.CallOption) (*ProductionPlanList, error) {
	out := new(ProductionPlanList)
	err := c.cc.Invoke(ctx, "/production_plan.production_plan/FindListByWorkshop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productionPlanClient) FindListByEnterprise(ctx context.Context, in *FindListByEnterpriseReq, opts ...grpc.CallOption) (*ProductionPlanList, error) {
	out := new(ProductionPlanList)
	err := c.cc.Invoke(ctx, "/production_plan.production_plan/FindListByEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductionPlanServer is the server API for ProductionPlan service.
// All implementations must embed UnimplementedProductionPlanServer
// for forward compatibility
type ProductionPlanServer interface {
	Insert(context.Context, *ProductionPlanInfo) (*InsertResp, error)
	Delete(context.Context, *DeleteReq) (*Empty, error)
	Update(context.Context, *ProductionPlanInfo) (*Empty, error)
	FindOneById(context.Context, *FindOneByIdReq) (*ProductionPlanInfo, error)
	FindListByWorkshop(context.Context, *FindListByWorkshopReq) (*ProductionPlanList, error)
	FindListByEnterprise(context.Context, *FindListByEnterpriseReq) (*ProductionPlanList, error)
	mustEmbedUnimplementedProductionPlanServer()
}

// UnimplementedProductionPlanServer must be embedded to have forward compatible implementations.
type UnimplementedProductionPlanServer struct {
}

func (UnimplementedProductionPlanServer) Insert(context.Context, *ProductionPlanInfo) (*InsertResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedProductionPlanServer) Delete(context.Context, *DeleteReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProductionPlanServer) Update(context.Context, *ProductionPlanInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProductionPlanServer) FindOneById(context.Context, *FindOneByIdReq) (*ProductionPlanInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOneById not implemented")
}
func (UnimplementedProductionPlanServer) FindListByWorkshop(context.Context, *FindListByWorkshopReq) (*ProductionPlanList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindListByWorkshop not implemented")
}
func (UnimplementedProductionPlanServer) FindListByEnterprise(context.Context, *FindListByEnterpriseReq) (*ProductionPlanList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindListByEnterprise not implemented")
}
func (UnimplementedProductionPlanServer) mustEmbedUnimplementedProductionPlanServer() {}

// UnsafeProductionPlanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductionPlanServer will
// result in compilation errors.
type UnsafeProductionPlanServer interface {
	mustEmbedUnimplementedProductionPlanServer()
}

func RegisterProductionPlanServer(s grpc.ServiceRegistrar, srv ProductionPlanServer) {
	s.RegisterService(&ProductionPlan_ServiceDesc, srv)
}

func _ProductionPlan_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductionPlanInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionPlanServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production_plan.production_plan/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionPlanServer).Insert(ctx, req.(*ProductionPlanInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionPlan_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionPlanServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production_plan.production_plan/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionPlanServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionPlan_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductionPlanInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionPlanServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production_plan.production_plan/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionPlanServer).Update(ctx, req.(*ProductionPlanInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionPlan_FindOneById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionPlanServer).FindOneById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production_plan.production_plan/FindOneById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionPlanServer).FindOneById(ctx, req.(*FindOneByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionPlan_FindListByWorkshop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindListByWorkshopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionPlanServer).FindListByWorkshop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production_plan.production_plan/FindListByWorkshop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionPlanServer).FindListByWorkshop(ctx, req.(*FindListByWorkshopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductionPlan_FindListByEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindListByEnterpriseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionPlanServer).FindListByEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/production_plan.production_plan/FindListByEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionPlanServer).FindListByEnterprise(ctx, req.(*FindListByEnterpriseReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductionPlan_ServiceDesc is the grpc.ServiceDesc for ProductionPlan service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductionPlan_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "production_plan.production_plan",
	HandlerType: (*ProductionPlanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _ProductionPlan_Insert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProductionPlan_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductionPlan_Update_Handler,
		},
		{
			MethodName: "FindOneById",
			Handler:    _ProductionPlan_FindOneById_Handler,
		},
		{
			MethodName: "FindListByWorkshop",
			Handler:    _ProductionPlan_FindListByWorkshop_Handler,
		},
		{
			MethodName: "FindListByEnterprise",
			Handler:    _ProductionPlan_FindListByEnterprise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "production_plan.proto",
}
