CREATE TABLE `staffer` (
    `id` INT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY (`id`),
    `enterprise_id` INT NOT NULL,
    `workshop_id` INT NOT NULL DEFAULT 0,
        INDEX `workshop_id_index`(`enterprise_id`, `workshop_id`),
    `username` VARCHAR(20) NOT NULL,
        UNIQUE KEY `username_unique_index`(`enterprise_id`, `username`),
    `role` VARCHAR(20) NOT NULL,
        -- INDEX `role_index`(`role`),
    `name` VARCHAR(20) NOT NULL,
        -- INDEX `name_index`(`name`),
    `hashed_password` VARCHAR(100) NOT NULL,
    `gender` VARCHAR(10),
    `phone_number` VARCHAR(20),
        -- INDEX `phone_number_index`(`phone_number`),
    `email` VARCHAR(254),
        -- INDEX `email_index`(`email`),
    `address` VARCHAR(100),
        -- INDEX `addrass_index`(`address`),
    `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `expire_time` INT NOT NULL DEFAULT 7200,
    `remark` VARCHAR(300),
        -- FULLTEXT INDEX `remark_fulltext_index`(`remark`),
    `version` INT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;