// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	enterprise "air-grating-pms-backend/api/organization/internal/handler/enterprise"
	workshop "air-grating-pms-backend/api/organization/internal/handler/workshop"
	"air-grating-pms-backend/api/organization/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/workshop",
				Handler: workshop.CreateWorkshopHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/workshop",
				Handler: workshop.ChangeWorkshopInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/workshop",
				Handler: workshop.PartialChangeWorkshopInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/workshop",
				Handler: workshop.DeleteWorkshopHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/workshop",
				Handler: workshop.RetrieveWorkshopHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/enterprise",
				Handler: enterprise.ChangeEnterpriseInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/enterprise",
				Handler: enterprise.PartialChangeEnterpriseInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/enterprise",
				Handler: enterprise.DeleteEnterpriseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/enterprise",
				Handler: enterprise.GetEnterpriseIdByNameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/enterprise",
				Handler: enterprise.CreateEnterpriseHandler(serverCtx),
			},
		},
	)
}
