// Code generated by goctl. DO NOT EDIT!

package enterprise

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	enterpriseFieldNames          = builder.RawFieldNames(&Enterprise{})
	enterpriseRows                = strings.Join(enterpriseFieldNames, ",")
	enterpriseRowsExpectAutoSet   = strings.Join(stringx.Remove(enterpriseFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	enterpriseRowsWithPlaceHolder = strings.Join(stringx.Remove(enterpriseFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheEnterpriseIdPrefix   = "cache:enterprise:id:"
	cacheEnterpriseNamePrefix = "cache:enterprise:name:"
)

type (
	enterpriseModel interface {
		Insert(ctx context.Context, data *Enterprise) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Enterprise, error)
		FindOneByName(ctx context.Context, name string) (*Enterprise, error)
		Update(ctx context.Context, data *Enterprise) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEnterpriseModel struct {
		sqlc.CachedConn
		table string
	}

	Enterprise struct {
		Id         int64          `db:"id"`
		Name       string         `db:"name"`
		Address    sql.NullString `db:"address"`
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
		Remark     sql.NullString `db:"remark"`
		Version    int64          `db:"version"`
	}
)

func newEnterpriseModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultEnterpriseModel {
	return &defaultEnterpriseModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`enterprise`",
	}
}

func (m *defaultEnterpriseModel) Insert(ctx context.Context, data *Enterprise) (sql.Result, error) {
	enterpriseIdKey := fmt.Sprintf("%s%v", cacheEnterpriseIdPrefix, data.Id)
	enterpriseNameKey := fmt.Sprintf("%s%v", cacheEnterpriseNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, enterpriseRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Address, data.Remark, data.Version)
	}, enterpriseIdKey, enterpriseNameKey)
	return ret, err
}

func (m *defaultEnterpriseModel) FindOne(ctx context.Context, id int64) (*Enterprise, error) {
	enterpriseIdKey := fmt.Sprintf("%s%v", cacheEnterpriseIdPrefix, id)
	var resp Enterprise
	err := m.QueryRowCtx(ctx, &resp, enterpriseIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", enterpriseRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEnterpriseModel) FindOneByName(ctx context.Context, name string) (*Enterprise, error) {
	enterpriseNameKey := fmt.Sprintf("%s%v", cacheEnterpriseNamePrefix, name)
	var resp Enterprise
	err := m.QueryRowIndexCtx(ctx, &resp, enterpriseNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", enterpriseRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEnterpriseModel) Update(ctx context.Context, data *Enterprise) error {
	enterpriseIdKey := fmt.Sprintf("%s%v", cacheEnterpriseIdPrefix, data.Id)
	enterpriseNameKey := fmt.Sprintf("%s%v", cacheEnterpriseNamePrefix, data.Name)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, enterpriseRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Address, data.Remark, data.Version, data.Id)
	}, enterpriseIdKey, enterpriseNameKey)
	return err
}

func (m *defaultEnterpriseModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	enterpriseIdKey := fmt.Sprintf("%s%v", cacheEnterpriseIdPrefix, id)
	enterpriseNameKey := fmt.Sprintf("%s%v", cacheEnterpriseNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, enterpriseIdKey, enterpriseNameKey)
	return err
}

func (m *defaultEnterpriseModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheEnterpriseIdPrefix, primary)
}

func (m *defaultEnterpriseModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", enterpriseRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultEnterpriseModel) tableName() string {
	return m.table
}
