// Code generated by goctl. DO NOT EDIT!
// Source: workshop.proto

package server

import (
	"context"

	"air-grating-pms-backend/rpc/workshop/internal/logic"
	"air-grating-pms-backend/rpc/workshop/internal/svc"
	"air-grating-pms-backend/rpc/workshop/types"
)

type WorkshopServer struct {
	svcCtx *svc.ServiceContext
	types.UnimplementedWorkshopServer
}

func NewWorkshopServer(svcCtx *svc.ServiceContext) *WorkshopServer {
	return &WorkshopServer{
		svcCtx: svcCtx,
	}
}

func (s *WorkshopServer) Insert(ctx context.Context, in *types.WorkshopInfo) (*types.Empty, error) {
	l := logic.NewInsertLogic(ctx, s.svcCtx)
	return l.Insert(in)
}

func (s *WorkshopServer) Delete(ctx context.Context, in *types.DeleteReq) (*types.Empty, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *WorkshopServer) Change(ctx context.Context, in *types.WorkshopInfoWithId) (*types.Empty, error) {
	l := logic.NewChangeLogic(ctx, s.svcCtx)
	return l.Change(in)
}

func (s *WorkshopServer) PartialChange(ctx context.Context, in *types.WorkshopInfoWithId) (*types.Empty, error) {
	l := logic.NewPartialChangeLogic(ctx, s.svcCtx)
	return l.PartialChange(in)
}

func (s *WorkshopServer) FindListByEnterprise(ctx context.Context, in *types.FindListByEnterpriseReq) (*types.WorkshopList, error) {
	l := logic.NewFindListByEnterpriseLogic(ctx, s.svcCtx)
	return l.FindListByEnterprise(in)
}
