// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: workshop.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorkshopClient is the client API for Workshop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkshopClient interface {
	Insert(ctx context.Context, in *WorkshopInfo, opts ...grpc.CallOption) (*InsertResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error)
	Update(ctx context.Context, in *WorkshopInfo, opts ...grpc.CallOption) (*Empty, error)
	FindListByEnterprise(ctx context.Context, in *FindListByEnterpriseReq, opts ...grpc.CallOption) (*WorkshopList, error)
}

type workshopClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkshopClient(cc grpc.ClientConnInterface) WorkshopClient {
	return &workshopClient{cc}
}

func (c *workshopClient) Insert(ctx context.Context, in *WorkshopInfo, opts ...grpc.CallOption) (*InsertResp, error) {
	out := new(InsertResp)
	err := c.cc.Invoke(ctx, "/workshop.workshop/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workshopClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/workshop.workshop/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workshopClient) Update(ctx context.Context, in *WorkshopInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/workshop.workshop/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workshopClient) FindListByEnterprise(ctx context.Context, in *FindListByEnterpriseReq, opts ...grpc.CallOption) (*WorkshopList, error) {
	out := new(WorkshopList)
	err := c.cc.Invoke(ctx, "/workshop.workshop/FindListByEnterprise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkshopServer is the server API for Workshop service.
// All implementations must embed UnimplementedWorkshopServer
// for forward compatibility
type WorkshopServer interface {
	Insert(context.Context, *WorkshopInfo) (*InsertResp, error)
	Delete(context.Context, *DeleteReq) (*Empty, error)
	Update(context.Context, *WorkshopInfo) (*Empty, error)
	FindListByEnterprise(context.Context, *FindListByEnterpriseReq) (*WorkshopList, error)
	mustEmbedUnimplementedWorkshopServer()
}

// UnimplementedWorkshopServer must be embedded to have forward compatible implementations.
type UnimplementedWorkshopServer struct {
}

func (UnimplementedWorkshopServer) Insert(context.Context, *WorkshopInfo) (*InsertResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedWorkshopServer) Delete(context.Context, *DeleteReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWorkshopServer) Update(context.Context, *WorkshopInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedWorkshopServer) FindListByEnterprise(context.Context, *FindListByEnterpriseReq) (*WorkshopList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindListByEnterprise not implemented")
}
func (UnimplementedWorkshopServer) mustEmbedUnimplementedWorkshopServer() {}

// UnsafeWorkshopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkshopServer will
// result in compilation errors.
type UnsafeWorkshopServer interface {
	mustEmbedUnimplementedWorkshopServer()
}

func RegisterWorkshopServer(s grpc.ServiceRegistrar, srv WorkshopServer) {
	s.RegisterService(&Workshop_ServiceDesc, srv)
}

func _Workshop_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkshopInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkshopServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workshop.workshop/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkshopServer).Insert(ctx, req.(*WorkshopInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workshop_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkshopServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workshop.workshop/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkshopServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workshop_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkshopInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkshopServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workshop.workshop/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkshopServer).Update(ctx, req.(*WorkshopInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workshop_FindListByEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindListByEnterpriseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkshopServer).FindListByEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workshop.workshop/FindListByEnterprise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkshopServer).FindListByEnterprise(ctx, req.(*FindListByEnterpriseReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Workshop_ServiceDesc is the grpc.ServiceDesc for Workshop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Workshop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workshop.workshop",
	HandlerType: (*WorkshopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _Workshop_Insert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Workshop_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Workshop_Update_Handler,
		},
		{
			MethodName: "FindListByEnterprise",
			Handler:    _Workshop_FindListByEnterprise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workshop.proto",
}
