CREATE TABLE `order` (
    `id` INT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY (`id`),
    `enterprise_id` INT NOT NULL,
    `workshop_id` INT NOT NULL,
        INDEX `workshop_id_index`(`enterprise_id`, `workshop_id`),
    `client_id` INT NOT NULL,
        -- INDEX `client_id_index`(`client_id`),
    `production_plan_id` INT NOT NULL DEFAULT 0,
        -- INDEX `production_plan_id_index`(`production_plan_id`),
    `state` INT NOT NULL DEFAULT 0,
        -- INDEX `state_index`(`state`),
    `address` VARCHAR(100) NOT NULL DEFAULT "",
        -- INDEX `addrass_index`(`address`),
    `linkman` VARCHAR(30) NOT NULL DEFAULT "",
        -- INDEX `linkman_index`(`linkman`),
    `phone_number` VARCHAR(20) NOT NULL DEFAULT "",
        -- INDEX `phone_number_index`(`phone_number`),
    `email` VARCHAR(254) NOT NULL DEFAULT "",
        -- INDEX `email_index`(`email`),
    `corresponding_code` VARCHAR(50) NOT NULL DEFAULT "",
    `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `remark` VARCHAR(200) NOT NULL DEFAULT "",
        -- FULLTEXT INDEX `remark_fulltext_index`(`remark`),
    `version` INT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;