CREATE TABLE `order` (
    `id` INT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY (`id`),
    `enterprise_id` INT NOT NULL,
    `workshop_id` INT NOT NULL,
        INDEX `workshop_id_index`(`enterprise_id`, `workshop_id`),
    `client_id` INT NOT NULL,
        -- INDEX `client_id_index`(`client_id`),
    `production_plan_id` INT,
        -- INDEX `production_plan_id_index`(`production_plan_id`),
    `state` INT NOT NULL DEFAULT 0,
        -- INDEX `state_index`(`state`),
    `address` VARCHAR(100),
        -- INDEX `addrass_index`(`address`),
    `linkman` VARCHAR(30),
        -- INDEX `linkman_index`(`linkman`),
    `phone_number` VARCHAR(20),
        -- INDEX `phone_number_index`(`phone_number`),
    `email` VARCHAR(254),
        -- INDEX `email_index`(`email`),
    `order_time` TIMESTAMP NOT NULL,
        -- INDEX `order_time_index`(`order_time`),
    `start_production_time` TIMESTAMP,
    `production_time` TIMESTAMP,
    `delivery_time` TIMESTAMP,
    `payment_tiem` TIMESTAMP,
    `corresponding_code` VARCHAR(50),
    `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `remark` VARCHAR(200),
        -- FULLTEXT INDEX `remark_fulltext_index`(`remark`),
    `version` INT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;