// Code generated by goctl. DO NOT EDIT!
// Source: production_plan.proto

package productionplan

import (
	"context"

	"air-grating-pms-backend/rpc/production_plan/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteReq               = pb.DeleteReq
	Empty                   = pb.Empty
	FindListByEnterpriseReq = pb.FindListByEnterpriseReq
	FindListByWorkshopReq   = pb.FindListByWorkshopReq
	FindOneByIdReq          = pb.FindOneByIdReq
	InsertResp              = pb.InsertResp
	ProductionPlanInfo      = pb.ProductionPlanInfo
	ProductionPlanList      = pb.ProductionPlanList

	ProductionPlan interface {
		Insert(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*InsertResp, error)
		Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error)
		Update(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*Empty, error)
		FindOneById(ctx context.Context, in *FindOneByIdReq, opts ...grpc.CallOption) (*ProductionPlanInfo, error)
		FindListByWorkshop(ctx context.Context, in *FindListByWorkshopReq, opts ...grpc.CallOption) (*ProductionPlanList, error)
		FindListByEnterprise(ctx context.Context, in *FindListByEnterpriseReq, opts ...grpc.CallOption) (*ProductionPlanList, error)
	}

	defaultProductionPlan struct {
		cli zrpc.Client
	}
)

func NewProductionPlan(cli zrpc.Client) ProductionPlan {
	return &defaultProductionPlan{
		cli: cli,
	}
}

func (m *defaultProductionPlan) Insert(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*InsertResp, error) {
	client := pb.NewProductionPlanClient(m.cli.Conn())
	return client.Insert(ctx, in, opts...)
}

func (m *defaultProductionPlan) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewProductionPlanClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}

func (m *defaultProductionPlan) Update(ctx context.Context, in *ProductionPlanInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewProductionPlanClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

func (m *defaultProductionPlan) FindOneById(ctx context.Context, in *FindOneByIdReq, opts ...grpc.CallOption) (*ProductionPlanInfo, error) {
	client := pb.NewProductionPlanClient(m.cli.Conn())
	return client.FindOneById(ctx, in, opts...)
}

func (m *defaultProductionPlan) FindListByWorkshop(ctx context.Context, in *FindListByWorkshopReq, opts ...grpc.CallOption) (*ProductionPlanList, error) {
	client := pb.NewProductionPlanClient(m.cli.Conn())
	return client.FindListByWorkshop(ctx, in, opts...)
}

func (m *defaultProductionPlan) FindListByEnterprise(ctx context.Context, in *FindListByEnterpriseReq, opts ...grpc.CallOption) (*ProductionPlanList, error) {
	client := pb.NewProductionPlanClient(m.cli.Conn())
	return client.FindListByEnterprise(ctx, in, opts...)
}
