// Code generated by goctl. DO NOT EDIT!
// Source: authentication.proto

package server

import (
	"context"

	"air-grating-pms-backend/rpc/authentication/internal/logic"
	"air-grating-pms-backend/rpc/authentication/internal/svc"
	"air-grating-pms-backend/rpc/authentication/types/authentication"
)

type AuthenticationServer struct {
	svcCtx *svc.ServiceContext
	authentication.UnimplementedAuthenticationServer
}

func NewAuthenticationServer(svcCtx *svc.ServiceContext) *AuthenticationServer {
	return &AuthenticationServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthenticationServer) Enforce(ctx context.Context, in *authentication.AuthReq) (*authentication.AuthResp, error) {
	l := logic.NewEnforceLogic(ctx, s.svcCtx)
	return l.Enforce(in)
}
