// Code generated by goctl. DO NOT EDIT!

package technology

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	technologyFieldNames          = builder.RawFieldNames(&Technology{})
	technologyRows                = strings.Join(technologyFieldNames, ",")
	technologyRowsExpectAutoSet   = strings.Join(stringx.Remove(technologyFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	technologyRowsWithPlaceHolder = strings.Join(stringx.Remove(technologyFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheTechnologyIdPrefix   = "cache:technology:id:"
	cacheTechnologyNamePrefix = "cache:technology:name:"
)

type (
	technologyModel interface {
		Insert(ctx context.Context, data *Technology) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Technology, error)
		FindOneByName(ctx context.Context, name string) (*Technology, error)
		Update(ctx context.Context, data *Technology) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTechnologyModel struct {
		sqlc.CachedConn
		table string
	}

	Technology struct {
		Id           int64          `db:"id"`
		EnterpriseId int64          `db:"enterprise_id"`
		WorkshopId   int64          `db:"workshop_id"`
		Name         string         `db:"name"`
		Info         sql.NullString `db:"info"`
		CreateTime   time.Time      `db:"create_time"`
		UpdateTime   time.Time      `db:"update_time"`
		Remark       sql.NullString `db:"remark"`
		Version      int64          `db:"version"`
	}
)

func newTechnologyModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTechnologyModel {
	return &defaultTechnologyModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`technology`",
	}
}

func (m *defaultTechnologyModel) Insert(ctx context.Context, data *Technology) (sql.Result, error) {
	technologyIdKey := fmt.Sprintf("%s%v", cacheTechnologyIdPrefix, data.Id)
	technologyNameKey := fmt.Sprintf("%s%v", cacheTechnologyNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, technologyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.EnterpriseId, data.WorkshopId, data.Name, data.Info, data.Remark, data.Version)
	}, technologyIdKey, technologyNameKey)
	return ret, err
}

func (m *defaultTechnologyModel) FindOne(ctx context.Context, id int64) (*Technology, error) {
	technologyIdKey := fmt.Sprintf("%s%v", cacheTechnologyIdPrefix, id)
	var resp Technology
	err := m.QueryRowCtx(ctx, &resp, technologyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", technologyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTechnologyModel) FindOneByName(ctx context.Context, name string) (*Technology, error) {
	technologyNameKey := fmt.Sprintf("%s%v", cacheTechnologyNamePrefix, name)
	var resp Technology
	err := m.QueryRowIndexCtx(ctx, &resp, technologyNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", technologyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTechnologyModel) Update(ctx context.Context, data *Technology) error {
	technologyIdKey := fmt.Sprintf("%s%v", cacheTechnologyIdPrefix, data.Id)
	technologyNameKey := fmt.Sprintf("%s%v", cacheTechnologyNamePrefix, data.Name)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, technologyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.EnterpriseId, data.WorkshopId, data.Name, data.Info, data.Remark, data.Version, data.Id)
	}, technologyIdKey, technologyNameKey)
	return err
}

func (m *defaultTechnologyModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	technologyIdKey := fmt.Sprintf("%s%v", cacheTechnologyIdPrefix, id)
	technologyNameKey := fmt.Sprintf("%s%v", cacheTechnologyNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, technologyIdKey, technologyNameKey)
	return err
}

func (m *defaultTechnologyModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheTechnologyIdPrefix, primary)
}

func (m *defaultTechnologyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", technologyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTechnologyModel) tableName() string {
	return m.table
}
