// Code generated by goctl. DO NOT EDIT.
package types

type InsertTechnologyReq struct {
	WorkshopId int64  `json:"workshop_id"`
	Name       string `json:"name"`
	Info       string `json:"info,optional"`
	Remark     string `json:"remark,optional"`
}

type InsertTechnologyReply struct {
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

type DeleteTechnologyReq struct {
	Id int64 `json:"id"`
}

type DeleteTechnologyReply struct {
	Message string `json:"message"`
}

type UpdateTechnologyReq struct {
	Id         int64  `json:"id"`
	WorkshopId int64  `json:"workshop_id,optional"`
	Name       string `json:"name,optional"`
	Info       string `json:"info,optional"`
	Remark     string `json:"remark,optional"`
}

type UpdateTechnologyReply struct {
	Message       string   `json:"message"`
	ChangedFields []string `json:"changed_fields"`
}

type GetTechnologyInfoByIdReq struct {
	Id int64 `json:"id"`
}

type TechnologyInfo struct {
	Id         int64  `json:"id"`
	WorkshopId int64  `json:"workshop_id"`
	Name       string `json:"name"`
	Info       string `json:"info"`
	Remark     string `json:"remark"`
	Version    int64  `json:"version"`
}

type GetTechnologyListByWorkshopReq struct {
	WorkshopId int64 `json:"workshop_id,optional"`
	PageNumber int32 `json:"pn"`
	PageSize   int32 `json:"ps"`
}

type GetTechnologyListByWorkshopReply struct {
	Message        string           `json:"message"`
	Count          int64            `json:"count"`
	TechnologyList []TechnologyInfo `json:"technology_list"`
}

type GetTechnologyListByEnterpriseReq struct {
	PageNumber int32 `json:"pn"`
	PageSize   int32 `json:"ps"`
}

type GetTechnologyListByEnterpriseReply struct {
	Message        string           `json:"message"`
	Count          int64            `json:"count"`
	TechnologyList []TechnologyInfo `json:"technology_list"`
}
